#!/usr/bin/env python3
"""
Phase 1 v2: Multi-User Profile Builder
=======================================
Just run:
    python3 scripts/build_profile_v2.py

The script will ask if you're creating a new profile or using an existing one,
then walk you through everything interactively.

Folder structure:
    profiles/{name}/
        resume.pdf (or .txt, .docx)
        cover_letter.pdf
        portfolio.txt
        linkedin.txt
        profile.json  ← generated by this script

Compatible with the full pipeline:
    build_profile_v2.py → score_jobs.py → tailor_resume.py → auto_apply_v4.py
"""

import json
import os
import sys
import argparse
import re
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import requests

# ── Config ───────────────────────────────────────────────────────────────────

OPENROUTER_API_KEY = os.environ.get("OPENROUTER_API_KEY", "")
OPENROUTER_BASE = "https://openrouter.ai/api/v1/chat/completions"
MODEL = "anthropic/claude-sonnet-4-5"

PROFILES_DIR = Path("profiles")

# Document detection patterns (filename contains these keywords)
DOC_PATTERNS = {
    "resume":       ["resume", "cv", "curriculum"],
    "cover_letter": ["cover", "letter", "cl"],
    "portfolio":    ["portfolio", "project", "work_sample"],
    "linkedin":     ["linkedin", "li_profile", "li_export"],
}

# Required documents — these must be present to proceed
REQUIRED_DOCS = ["resume", "cover_letter"]

# Optional but encouraged
OPTIONAL_DOCS = ["portfolio", "linkedin"]

# Supported file extensions
SUPPORTED_EXTENSIONS = {".txt", ".md", ".pdf", ".docx", ".doc", ".rtf", ".html", ".htm"}

# Labels for display
DOC_LABELS = {
    "resume": "Resume",
    "cover_letter": "Cover Letter",
    "portfolio": "Portfolio",
    "linkedin": "LinkedIn Profile",
}


# ── File Readers ─────────────────────────────────────────────────────────────

def read_text_file(path):
    """Read plain text, markdown, or RTF files."""
    return Path(path).read_text(encoding="utf-8", errors="replace")


def read_pdf_file(path):
    """Read PDF files using pdfminer.six."""
    try:
        from pdfminer.high_level import extract_text
        return extract_text(str(path))
    except ImportError:
        print("  ⚠️  PDF support requires pdfminer. Install with:")
        print("     pip3 install pdfminer.six --break-system-packages")
        return ""


def read_docx_file(path):
    """Read DOCX files using python-docx."""
    try:
        from docx import Document
        doc = Document(str(path))
        return "\n".join(para.text for para in doc.paragraphs if para.text.strip())
    except ImportError:
        print("  ⚠️  DOCX support requires python-docx. Install with:")
        print("     pip3 install python-docx --break-system-packages")
        return ""


def read_html_file(path):
    """
    Read an HTML file and extract meaningful text content.
    Uses BeautifulSoup if available, falls back to Python's built-in html.parser.
    """
    raw_html = Path(path).read_text(encoding="utf-8", errors="replace")

    # Try BeautifulSoup first (better quality extraction)
    try:
        from bs4 import BeautifulSoup
        soup = BeautifulSoup(raw_html, "html.parser")

        # Remove script and style elements
        for tag in soup(["script", "style", "nav", "footer", "header"]):
            tag.decompose()

        # Get text with newlines between block elements
        text = soup.get_text(separator="\n", strip=True)

        # Clean up excessive blank lines
        lines = [line.strip() for line in text.splitlines()]
        lines = [line for line in lines if line]
        return "\n".join(lines)

    except ImportError:
        pass

    # Fallback: Python built-in html.parser
    from html.parser import HTMLParser

    class HTMLTextExtractor(HTMLParser):
        def __init__(self):
            super().__init__()
            self.result = []
            self._skip = False
            self._skip_tags = {"script", "style", "nav", "footer"}

        def handle_starttag(self, tag, attrs):
            if tag in self._skip_tags:
                self._skip = True
            # Add newline before block-level elements
            if tag in ("p", "div", "h1", "h2", "h3", "h4", "h5", "h6",
                        "li", "tr", "br", "section", "article"):
                self.result.append("\n")

        def handle_endtag(self, tag):
            if tag in self._skip_tags:
                self._skip = False

        def handle_data(self, data):
            if not self._skip:
                self.result.append(data)

    extractor = HTMLTextExtractor()
    extractor.feed(raw_html)
    text = "".join(extractor.result)

    # Clean up
    lines = [line.strip() for line in text.splitlines()]
    lines = [line for line in lines if line]
    return "\n".join(lines)


def read_file(path):
    """Read any supported file type and return its text content."""
    path = Path(path)
    ext = path.suffix.lower()

    if ext in (".txt", ".md"):
        return read_text_file(path)
    elif ext == ".pdf":
        return read_pdf_file(path)
    elif ext in (".docx", ".doc"):
        return read_docx_file(path)
    elif ext in (".html", ".htm"):
        return read_html_file(path)
    elif ext == ".rtf":
        return read_text_file(path)
    else:
        print("  ⚠️  Unsupported file type: {}".format(ext))
        return ""


# ── Document Discovery ───────────────────────────────────────────────────────

def discover_documents(user_dir):
    """
    Scan a user's folder and classify files by type.
    Returns dict: {"resume": Path, "cover_letter": Path, ...}
    Also returns a list of unclassified files.
    """
    user_dir = Path(user_dir)
    if not user_dir.exists():
        return {}, []

    classified = {}
    other_files = []

    for file_path in sorted(user_dir.iterdir()):
        if file_path.is_dir():
            continue
        if file_path.name.startswith("."):
            continue
        if file_path.name in ("profile.json", "scored_jobs.json"):
            continue
        if file_path.suffix.lower() not in SUPPORTED_EXTENSIONS:
            continue

        name_lower = file_path.stem.lower().replace("-", "_").replace(" ", "_")
        matched = False

        for doc_type, keywords in DOC_PATTERNS.items():
            if any(kw in name_lower for kw in keywords):
                if doc_type not in classified:
                    classified[doc_type] = file_path
                    matched = True
                    break

        if not matched:
            other_files.append(file_path)

    return classified, other_files


def validate_required_documents(classified):
    """
    Check that required documents are present.
    Returns (missing_list, found_list, optional_missing, optional_found).
    """
    found = []
    missing = []

    for doc_type in REQUIRED_DOCS:
        label = DOC_LABELS.get(doc_type, doc_type)
        if doc_type in classified:
            found.append((doc_type, label, classified[doc_type].name))
        else:
            missing.append((doc_type, label))

    optional_found = []
    optional_missing = []
    for doc_type in OPTIONAL_DOCS:
        label = DOC_LABELS.get(doc_type, doc_type)
        if doc_type in classified:
            optional_found.append((doc_type, label, classified[doc_type].name))
        else:
            optional_missing.append((doc_type, label))

    return missing, found, optional_missing, optional_found


def display_discovered_files(classified, other_files):
    """Show user what files were found and how they were classified."""
    print("\n  📂 Documents found:")
    print("  " + "─" * 50)

    for doc_type, path in classified.items():
        label = DOC_LABELS.get(doc_type, doc_type)
        emoji = {"resume": "📄", "cover_letter": "✉️ ", "portfolio": "💼", "linkedin": "🔗"}.get(doc_type, "📎")
        print("    {} {}: {}".format(emoji, label, path.name))

    if other_files:
        print("\n    📎 Additional files (will also be analyzed):")
        for f in other_files:
            print("       {}".format(f.name))

    return bool(classified) or bool(other_files)


# ── Claude API ───────────────────────────────────────────────────────────────

def ask_claude(prompt, max_tokens=4000, temperature=0.2):
    """Send a prompt to Claude via OpenRouter and return the response text."""
    if not OPENROUTER_API_KEY:
        print("❌ OPENROUTER_API_KEY not set. Run:")
        print("   export OPENROUTER_API_KEY=your_key")
        sys.exit(1)

    resp = requests.post(
        OPENROUTER_BASE,
        headers={
            "Authorization": "Bearer {}".format(OPENROUTER_API_KEY),
            "Content-Type": "application/json",
        },
        json={
            "model": MODEL,
            "messages": [{"role": "user", "content": prompt}],
            "max_tokens": max_tokens,
            "temperature": temperature,
        },
        timeout=60,
    )

    try:
        data = resp.json()
        return data["choices"][0]["message"]["content"].strip()
    except (KeyError, IndexError):
        print("  ❌ Claude API error: {}".format(resp.text[:500]))
        return ""


def parse_json_response(raw):
    """Extract JSON from Claude's response, handling markdown fences."""
    raw = raw.strip()
    if "```" in raw:
        parts = raw.split("```")
        for part in parts:
            cleaned = part.strip()
            if cleaned.startswith("json"):
                cleaned = cleaned[4:].strip()
            if cleaned.startswith("{"):
                raw = cleaned
                break

    start = raw.find("{")
    end = raw.rfind("}") + 1
    if start >= 0 and end > start:
        try:
            return json.loads(raw[start:end])
        except json.JSONDecodeError:
            pass

    try:
        return json.loads(raw)
    except json.JSONDecodeError as e:
        print("  ⚠️  Could not parse Claude's JSON: {}".format(str(e)[:100]))
        return None


# ── Profile Extraction ───────────────────────────────────────────────────────

def extract_profile_from_docs(documents):
    """
    Send all documents to Claude and get a structured profile extraction.
    This is the initial extraction BEFORE interactive Q&A.
    """
    doc_sections = []
    for doc_type, content in documents.items():
        if content and content.strip():
            truncated = content[:4000]
            doc_sections.append("## {}\n{}".format(doc_type.upper().replace("_", " "), truncated))

    all_docs = "\n\n".join(doc_sections)

    prompt = """You are a career coach and recruiter. Analyze these documents from a job seeker
and extract a structured profile. Pull out EVERY detail you can find.

{docs}

Return ONLY a valid JSON object (no explanation, no backticks) with this structure:

{{
  "personal": {{
    "name": "",
    "email": "",
    "phone": "",
    "location": "",
    "linkedin_url": "",
    "portfolio_url": "",
    "github_url": ""
  }},
  "extracted_roles": ["roles they've held or seem qualified for"],
  "experience_level": "Entry-Level / Mid-Level / Senior / Lead",
  "years_of_experience": 0,
  "hard_skills": ["every technical skill mentioned"],
  "soft_skills": ["every soft skill mentioned or implied"],
  "industries": ["industries they have experience in"],
  "education": ["degree - school - year"],
  "certifications": ["cert name - issuer - year if known"],
  "work_history": [
    {{
      "title": "",
      "company": "",
      "duration": "",
      "location": ""
    }}
  ],
  "keywords": ["important keywords for job searching"],
  "summary": "A 2-3 sentence professional summary of this candidate"
}}""".format(docs=all_docs)

    print("\n  🤖 Analyzing your documents with Claude...")
    raw = ask_claude(prompt, max_tokens=4000)
    return parse_json_response(raw)


def suggest_adjacent_roles(target_roles, hard_skills, industries):
    """Ask Claude to suggest 3 adjacent roles based on the candidate's background."""
    prompt = """Based on this candidate's background, suggest exactly 3 adjacent job titles
they should ALSO consider searching for. These should be realistic lateral moves
or natural progressions — not aspirational stretch roles.

Their background:
- Target/current roles: {roles}
- Key skills: {skills}
- Industries: {industries}

Return ONLY a JSON array of 3 objects, no explanation:
[
  {{"title": "Role Title", "reason": "One sentence why this fits"}},
  {{"title": "Role Title", "reason": "One sentence why this fits"}},
  {{"title": "Role Title", "reason": "One sentence why this fits"}}
]""".format(
        roles=", ".join(target_roles[:5]),
        skills=", ".join(hard_skills[:10]),
        industries=", ".join(industries[:5]),
    )

    raw = ask_claude(prompt, max_tokens=500)

    raw = raw.strip()
    if "```" in raw:
        parts = raw.split("```")
        for part in parts:
            cleaned = part.strip()
            if cleaned.startswith("json"):
                cleaned = cleaned[4:].strip()
            if cleaned.startswith("["):
                raw = cleaned
                break

    start = raw.find("[")
    end = raw.rfind("]") + 1
    if start >= 0 and end > start:
        try:
            return json.loads(raw[start:end])
        except json.JSONDecodeError:
            pass

    return []


# ── Interactive Helpers ──────────────────────────────────────────────────────

def ask_user(question, default="", show_default=True):
    """Ask the user a question with an optional default value."""
    if default and show_default:
        prompt_text = "\n  ❓ {} [{}]: ".format(question, default)
    else:
        prompt_text = "\n  ❓ {}: ".format(question)

    answer = input(prompt_text).strip()
    return answer if answer else default


def ask_user_yes_no(question, default="y"):
    """Ask a yes/no question."""
    suffix = "[Y/n]" if default.lower() == "y" else "[y/N]"
    answer = input("\n  ❓ {} {}: ".format(question, suffix)).strip().lower()
    if not answer:
        return default.lower() == "y"
    return answer in ("y", "yes", "yeah", "yep", "sure")


def parse_choice_number(answer):
    """
    Parse a number from user input, stripping periods, commas, and whitespace.
    Handles inputs like '4', '4.', ' 3 ', '2,', etc.
    Returns the integer or None if not parseable.
    """
    cleaned = answer.strip().rstrip(".").rstrip(",").strip()
    try:
        return int(cleaned)
    except ValueError:
        return None


def ask_user_choice(question, options):
    """
    Present numbered options for the user to choose from.
    Handles common input quirks like trailing periods.
    """
    print("\n  ❓ {}".format(question))
    for i, option in enumerate(options, 1):
        print("     {}. {}".format(i, option))

    while True:
        answer = input("  → ").strip()
        num = parse_choice_number(answer)
        if num is not None and 1 <= num <= len(options):
            return num - 1  # Return 0-indexed

        # Try matching by text (e.g., user types "Remote only")
        answer_lower = answer.lower()
        for i, option in enumerate(options):
            if answer_lower == option.lower() or answer_lower in option.lower():
                return i

        print("  ⚠️  Please enter a number between 1 and {}".format(len(options)))


def is_accept_all_phrase(text):
    """Check if the user typed something meaning 'accept all the defaults'."""
    phrases = [
        "all", "all three", "all of them", "all of those",
        "all the above", "all of the above", "yes all",
        "yeah all", "all those", "all 3", "all five", "all 5",
    ]
    return text.strip().lower() in phrases


def parse_salary(s):
    """Parse a salary string into an integer. Handles $, commas, k/K shorthand."""
    if not s:
        return 0
    cleaned = s.strip().replace(",", "").replace("$", "")
    # Handle 85k or 85K → 85000
    if cleaned.lower().endswith("k"):
        cleaned = cleaned[:-1]
        try:
            return int(float(cleaned) * 1000)
        except ValueError:
            return 0
    try:
        return int(cleaned)
    except ValueError:
        return 0


# ── Startup Menu ─────────────────────────────────────────────────────────────

def find_existing_folders():
    """Find all profile directories (even those without a profile.json yet)."""
    folders = []
    if not PROFILES_DIR.exists():
        return folders

    for item in sorted(PROFILES_DIR.iterdir()):
        if item.is_dir() and not item.name.startswith("."):
            has_profile = (item / "profile.json").exists()

            # Try to get display info from existing profile
            display_name = item.name.title()
            roles_preview = ""
            if has_profile:
                try:
                    profile = json.loads((item / "profile.json").read_text())
                    display_name = profile.get("personal", {}).get("name", display_name)
                    roles = profile.get("target_roles", [])
                    if roles:
                        roles_preview = ", ".join(roles[:2])
                except (json.JSONDecodeError, IOError):
                    pass

            folders.append({
                "dir_name": item.name,
                "display_name": display_name,
                "roles_preview": roles_preview,
                "path": item,
                "has_profile": has_profile,
            })

    return folders


def run_startup_menu():
    """
    Interactive startup menu:
    1. New person or existing?
    2. If new → ask name, create folder
    3. If existing → show list, pick one
    Returns (user_dir, dir_name, has_existing_profile) or None to exit.
    """
    print("\n  👋 Welcome to Job Bot Profile Builder!")
    print("  " + "─" * 50)

    existing = find_existing_folders()

    if existing:
        print("\n  ❓ What would you like to do?")
        print("     1. 🆕 Create a new profile for a new person")
        print("     2. 📂 Choose an existing person")

        while True:
            answer = input("  → ").strip()
            num = parse_choice_number(answer)
            if num == 1:
                return _create_new_person()
            elif num == 2:
                return _choose_existing_person(existing)
            else:
                print("  ⚠️  Please enter 1 or 2")
    else:
        print("\n  No existing profiles found. Let's create one!")
        return _create_new_person()


def _create_new_person():
    """Ask for a name and create the folder."""
    while True:
        name = input("\n  ❓ What is this person's first name?: ").strip()
        if not name:
            print("  ⚠️  A name is required.")
            continue

        dir_name = name.lower().replace(" ", "_")
        user_dir = PROFILES_DIR / dir_name

        if user_dir.exists():
            print("  ⚠️  A folder for '{}' already exists at {}".format(name, user_dir))
            if ask_user_yes_no("Use this existing folder?", "y"):
                has_profile = (user_dir / "profile.json").exists()
                return user_dir, dir_name, has_profile
            else:
                continue

        user_dir.mkdir(parents=True, exist_ok=True)
        print("  ✅ Created folder: {}".format(user_dir))
        return user_dir, dir_name, False


def _choose_existing_person(folders):
    """Show existing profiles and let user pick one."""
    print("\n  📂 Existing profiles:")
    print("  " + "─" * 50)

    for i, folder in enumerate(folders, 1):
        status = "✅ has profile" if folder["has_profile"] else "📝 no profile yet"
        roles_info = ""
        if folder["roles_preview"]:
            roles_info = " → {}".format(folder["roles_preview"])
        print("     {}. {} ({}{})".format(
            i, folder["display_name"], status, roles_info
        ))

    while True:
        answer = input("\n  → Pick a number: ").strip()
        num = parse_choice_number(answer)
        if num is not None and 1 <= num <= len(folders):
            chosen = folders[num - 1]
            return chosen["path"], chosen["dir_name"], chosen["has_profile"]
        print("  ⚠️  Please enter a number between 1 and {}".format(len(folders)))


# ── Document Check Flow ─────────────────────────────────────────────────────

def run_document_check(user_dir):
    """
    Ask if documents are uploaded, validate them, and return the results.
    Returns (classified, other_files) or None if user needs to upload first.
    """
    print("\n  📁 Profile folder: {}".format(user_dir))
    print("  " + "─" * 50)
    print("  Before we begin, drop these files into the folder above:")
    print("    • Resume (.pdf, .docx, or .txt)")
    print("    • Cover Letter (.pdf, .docx, or .txt)")
    print("    • Portfolio (optional — .html, .txt, .pdf, or .docx)")
    print("    • LinkedIn export (optional — .txt)")
    print("")
    print("  💡 Tip: Name files clearly so they get detected automatically.")
    print("     e.g., resume.pdf, cover_letter.docx, portfolio.html")

    while True:
        ready = ask_user_yes_no(
            "Have you uploaded your resume, cover letter, and portfolio?", "y"
        )

        if not ready:
            print("\n  📂 No worries! Please upload your resume, cover letter,")
            print("     and portfolio into this folder before moving forward:")
            print("     → {}".format(user_dir.resolve()))
            if not ask_user_yes_no("Want to try again?", "y"):
                return None
            continue

        # User said yes — scan the folder
        classified, other_files = discover_documents(user_dir)

        # Check for required documents
        missing, found, opt_missing, opt_found = validate_required_documents(classified)

        if missing:
            # User said yes but we can't find required files
            print("\n  ⚠️  You said yes, but we can't find your:")
            for doc_type, label in missing:
                print("     ❌ {}".format(label))
            print("\n  Please check the {} directory for any mistakes.".format(user_dir))
            print("  Make sure filenames contain keywords like 'resume' or 'cover'.")
            print("  Supported formats: .txt, .pdf, .docx, .html, .md")

            # Show what WAS found
            if found:
                print("\n  ✅ We did find:")
                for doc_type, label, filename in found:
                    print("     {} → {}".format(label, filename))

            if not ask_user_yes_no("Want to try again after fixing the files?", "y"):
                # Let them continue without all files if they have at least something
                if found:
                    if ask_user_yes_no("Continue with just the files we found?", "y"):
                        break
                return None
            continue

        # All required docs found!
        break

    # Display what we found
    display_discovered_files(classified, other_files)

    # Report optional missing docs (informational only)
    if opt_missing:
        print("\n  💡 Optional (not found, but that's OK):")
        for doc_type, label in opt_missing:
            print("     ○ {}".format(label))

    return classified, other_files


# ── Interactive Q&A ──────────────────────────────────────────────────────────

def run_interactive_qa(extracted):
    """
    Run the interactive Q&A session to refine the profile.
    Takes the Claude-extracted data and lets the user confirm/edit everything.
    Returns a complete profile dict ready to save.
    """
    print("\n" + "=" * 55)
    print("  🎯 Let's build your job search profile!")
    print("  (Press Enter to accept defaults shown in [brackets])")
    print("=" * 55)

    personal = extracted.get("personal", {})

    # ── Personal Info ────────────────────────────────────────────────────

    print("\n  👤 PERSONAL INFORMATION")
    print("  " + "─" * 50)

    name = ask_user("Full name", personal.get("name", ""))
    email = ask_user("Email", personal.get("email", ""))
    phone = ask_user("Phone", personal.get("phone", ""))
    location = ask_user("Current location (city, state)", personal.get("location", ""))
    linkedin = ask_user("LinkedIn URL", personal.get("linkedin_url", ""))
    portfolio = ask_user("Portfolio URL (leave blank if none)", personal.get("portfolio_url", ""))
    github = ask_user("GitHub URL (leave blank if none)", personal.get("github_url", ""))

    # ── Target Roles ─────────────────────────────────────────────────────

    print("\n  🎯 TARGET ROLES")
    print("  " + "─" * 50)

    extracted_roles = extracted.get("extracted_roles", [])
    default_roles = extracted_roles[:3]

    if extracted_roles:
        print("\n  Based on your documents, you seem qualified for:")
        for i, role in enumerate(extracted_roles[:5], 1):
            print("    {}. {}".format(i, role))

    default_display = ", ".join(default_roles) if default_roles else ""
    if extracted_roles:
        print("\n  💡 Press Enter to accept the top 3, type 'all' for all {},".format(
            len(extracted_roles[:5])))
        print("     or type your own roles (comma-separated).")

    role_input = ask_user(
        "What role(s) are you looking for? (comma-separated)",
        default_display,
    )

    # Handle "all" / "all three" / "all five" / etc.
    if is_accept_all_phrase(role_input):
        target_roles = list(extracted_roles[:5])
        print("  ✅ Using all detected roles: {}".format(", ".join(target_roles)))
    else:
        target_roles = [r.strip() for r in role_input.split(",") if r.strip()]

    # Suggest adjacent roles
    if target_roles:
        print("\n  🔍 Finding related roles you might also want to consider...")
        suggestions = suggest_adjacent_roles(
            target_roles,
            extracted.get("hard_skills", []),
            extracted.get("industries", []),
        )

        if suggestions:
            print("\n  💡 You might also want to search for:")
            for i, s in enumerate(suggestions, 1):
                print("     {}. {} — {}".format(i, s.get("title", ""), s.get("reason", "")))

            add_choices = ask_user(
                "Add any of these? (enter numbers like 1,3 or 'all' or 'none')",
                "none",
                show_default=False,
            )

            if is_accept_all_phrase(add_choices):
                for s in suggestions:
                    title = s.get("title", "")
                    if title and title not in target_roles:
                        target_roles.append(title)
                print("  ✅ Added all {} suggestions".format(len(suggestions)))
            elif add_choices.lower() != "none" and add_choices.strip():
                try:
                    indices = [int(x.strip().rstrip(".")) - 1 for x in add_choices.split(",")]
                    for idx in indices:
                        if 0 <= idx < len(suggestions):
                            title = suggestions[idx].get("title", "")
                            if title and title not in target_roles:
                                target_roles.append(title)
                                print("  ✅ Added: {}".format(title))
                except ValueError:
                    print("  ⏭️  Skipping suggestions")

    # ── Work Preferences ─────────────────────────────────────────────────

    print("\n  🏠 WORK PREFERENCES")
    print("  " + "─" * 50)

    remote_options = ["Remote only", "Hybrid", "In-person only", "Open to all"]
    remote_idx = ask_user_choice("What's your work arrangement preference?", remote_options)
    remote_preference = remote_options[remote_idx]

    # Location preferences
    print("\n  📍 LOCATION")
    print("  " + "─" * 50)

    if location:
        print("  Your current location: {}".format(location))

    pref_loc_input = ask_user(
        "What locations are you willing to work in? (comma-separated, include 'Remote' if applicable)",
        "{}, Remote".format(location) if location else "Remote",
    )
    preferred_locations = [loc.strip() for loc in pref_loc_input.split(",") if loc.strip()]

    # ── Experience ────────────────────────────────────────────────────────

    print("\n  📊 EXPERIENCE")
    print("  " + "─" * 50)

    years_str = ask_user(
        "Total years of professional experience",
        str(extracted.get("years_of_experience", 0)),
    )
    try:
        years = int(years_str)
    except ValueError:
        years = 0

    if years <= 1:
        default_level = "Entry-Level"
    elif years <= 4:
        default_level = "Mid-Level"
    elif years <= 8:
        default_level = "Senior"
    else:
        default_level = "Lead"

    exp_level = ask_user(
        "Experience level (Entry-Level / Mid-Level / Senior / Lead)",
        extracted.get("experience_level", default_level),
    )

    # ── Salary ────────────────────────────────────────────────────────────

    print("\n  💰 SALARY")
    print("  " + "─" * 50)
    print("  Enter your desired salary range. Leave blank to skip.")
    print("  You can use shorthand like 85k or full numbers like 85000.")

    salary_min_str = ask_user("Minimum salary (USD)", "", show_default=False)
    salary_min = parse_salary(salary_min_str)

    salary_max_str = ask_user("Maximum/ideal salary (USD)", "", show_default=False)
    salary_max = parse_salary(salary_max_str)

    # Show confirmation of what was parsed
    if salary_min and salary_max:
        print("  ✅ Range: ${:,} – ${:,}".format(salary_min, salary_max))
    elif salary_min:
        print("  ✅ Minimum: ${:,}+".format(salary_min))
    elif salary_max:
        print("  ✅ Up to: ${:,}".format(salary_max))
    else:
        print("  ✅ No salary preference set — that's fine!")

    # ── Work Authorization ────────────────────────────────────────────────

    print("\n  🛂 WORK AUTHORIZATION")
    print("  " + "─" * 50)

    us_authorized = ask_user_yes_no("Are you authorized to work in the US?", "y")
    needs_sponsorship = False
    if us_authorized:
        needs_sponsorship = ask_user_yes_no("Do you require visa sponsorship?", "n")
    us_citizen = ask_user_yes_no("Are you a US citizen or permanent resident?", "y")

    # ── Skills Review ─────────────────────────────────────────────────────

    print("\n  🛠️  SKILLS")
    print("  " + "─" * 50)

    hard_skills = extracted.get("hard_skills", [])
    if hard_skills:
        print("\n  Technical skills detected from your documents:")
        for i in range(0, len(hard_skills), 3):
            chunk = hard_skills[i:i + 3]
            print("    " + "  |  ".join(chunk))

        edit_skills = ask_user_yes_no("Want to add or remove any skills?", "n")
        if edit_skills:
            add_skills = ask_user("Skills to ADD (comma-separated, or leave blank)", "")
            if add_skills:
                for skill in add_skills.split(","):
                    skill = skill.strip()
                    if skill and skill not in hard_skills:
                        hard_skills.append(skill)

            remove_skills = ask_user("Skills to REMOVE (comma-separated, or leave blank)", "")
            if remove_skills:
                remove_list = [s.strip().lower() for s in remove_skills.split(",")]
                hard_skills = [s for s in hard_skills if s.lower() not in remove_list]

    # ── Deal Breakers ─────────────────────────────────────────────────────

    print("\n  🚫 DEAL BREAKERS")
    print("  " + "─" * 50)

    deal_input = ask_user(
        "Any deal breakers? (comma-separated, e.g. 'no travel, no clearance required')\n"
        "     Leave blank if none",
        "",
        show_default=False,
    )
    deal_breakers = [d.strip() for d in deal_input.split(",") if d.strip()] if deal_input else []

    # ── Additional Questions (learn-as-you-go seed) ──────────────────────

    print("\n  📝 COMMON APPLICATION QUESTIONS")
    print("  " + "─" * 50)
    print("  These pre-fill answers for job applications so you don't get asked later.")

    extra_answers = {}
    common_questions = [
        ("How did you hear about this job?", "LinkedIn"),
        ("Do you have a security clearance or are you eligible?", ""),
        ("Are you willing to undergo a background check?", "Yes"),
    ]

    for question, default in common_questions:
        answer = ask_user(question, default)
        if answer:
            extra_answers[question] = answer

    while ask_user_yes_no("Add another pre-filled answer?", "n"):
        q = ask_user("Question (as it might appear on an application)", "")
        if q:
            a = ask_user("Your answer", "")
            if a:
                extra_answers[q] = a

    # ── Build Final Profile ───────────────────────────────────────────────

    profile = {
        "personal": {
            "name": name,
            "email": email,
            "phone": phone,
            "location": location,
            "linkedin_url": linkedin,
            "portfolio_url": portfolio,
            "github_url": github,
        },
        "target_roles": target_roles,
        "experience_level": exp_level,
        "years_of_experience": years,
        "hard_skills": hard_skills,
        "soft_skills": extracted.get("soft_skills", []),
        "industries": extracted.get("industries", []),
        "education": extracted.get("education", []),
        "certifications": extracted.get("certifications", []),
        "preferred_locations": preferred_locations,
        "remote_preference": remote_preference,
        "salary_range": {
            "min": salary_min,
            "max": salary_max,
            "currency": "USD",
        },
        "keywords": extracted.get("keywords", []),
        "deal_breakers": deal_breakers,
        "summary": extracted.get("summary", ""),
        "extra_answers": extra_answers,
        "work_authorization": {
            "authorized_to_work_in_us": us_authorized,
            "requires_sponsorship": needs_sponsorship,
            "us_citizen_or_permanent_resident": us_citizen,
            "countries_authorized": ["United States"] if us_authorized else [],
            "notes": "",
        },
        "work_history": extracted.get("work_history", []),
    }

    return profile


# ── Display Summary ──────────────────────────────────────────────────────────

def display_profile_summary(profile):
    """Show a nice summary of the completed profile."""
    p = profile.get("personal", {})
    print("\n" + "=" * 55)
    print("  ✅ PROFILE COMPLETE")
    print("=" * 55)
    print("  Name:           {}".format(p.get("name", "N/A")))
    print("  Location:       {}".format(p.get("location", "N/A")))
    print("  Target Roles:   {}".format(", ".join(profile.get("target_roles", []))))
    print("  Experience:     {} ({} years)".format(
        profile.get("experience_level", ""),
        profile.get("years_of_experience", 0),
    ))
    print("  Remote Pref:    {}".format(profile.get("remote_preference", "")))
    print("  Locations:      {}".format(", ".join(profile.get("preferred_locations", []))))

    salary = profile.get("salary_range", {})
    sal_min = salary.get("min", 0)
    sal_max = salary.get("max", 0)
    if sal_min and sal_max:
        print("  Salary Range:   ${:,} – ${:,}".format(sal_min, sal_max))
    elif sal_min:
        print("  Salary Min:     ${:,}+".format(sal_min))
    elif sal_max:
        print("  Salary Max:     ${:,}".format(sal_max))
    else:
        print("  Salary Range:   Not specified")

    skills = profile.get("hard_skills", [])
    if skills:
        print("  Top Skills:     {}".format(", ".join(skills[:6])))

    certs = profile.get("certifications", [])
    if certs:
        print("  Certifications: {}".format(", ".join(certs[:4])))

    extra = profile.get("extra_answers", {})
    if extra:
        print("  Pre-filled Q&A: {} answers saved".format(len(extra)))

    print("  " + "─" * 50)


# ── Migration Helper ─────────────────────────────────────────────────────────

def migrate_old_profile(old_profile_path, user_name):
    """Migrate the old profiles/job_profile.json into profiles/{name}/."""
    old_path = Path(old_profile_path)
    if not old_path.exists():
        return False

    new_dir = PROFILES_DIR / user_name
    new_dir.mkdir(parents=True, exist_ok=True)
    new_path = new_dir / "profile.json"

    if new_path.exists():
        print("  ⚠️  Profile already exists at {}".format(new_path))
        return False

    profile = json.loads(old_path.read_text())
    new_path.write_text(json.dumps(profile, indent=2))
    print("  ✅ Migrated {} → {}".format(old_path, new_path))
    return True


# ── Main ─────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Build a job search profile from your documents",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Interactive mode (recommended)
  python3 scripts/build_profile_v2.py

  # Skip the menu — go straight to a specific person
  python3 scripts/build_profile_v2.py --name hannah

  # Rebuild from scratch
  python3 scripts/build_profile_v2.py --name hannah --rebuild

  # Migrate old profile to new folder structure
  python3 scripts/build_profile_v2.py --migrate alex
        """,
    )
    parser.add_argument("--name", required=False,
                        help="Person's name (skips startup menu)")
    parser.add_argument("--rebuild", action="store_true",
                        help="Rebuild profile from scratch even if one exists")
    parser.add_argument("--migrate", metavar="NAME",
                        help="Migrate old profiles/job_profile.json to profiles/{NAME}/")

    args = parser.parse_args()

    print("\n🚀 Job Bot — Profile Builder v2")
    print("=" * 55)

    # ── Handle migration ─────────────────────────────────────────────

    if args.migrate:
        migrate_old_profile("profiles/job_profile.json", args.migrate)
        print("\n  ➡️  Now run: python3 scripts/build_profile_v2.py --name {}".format(args.migrate))
        return

    # ── Determine user via menu or --name flag ───────────────────────

    if args.name:
        # Direct mode — skip menu
        dir_name = args.name.lower().replace(" ", "_")
        user_dir = PROFILES_DIR / dir_name
        user_dir.mkdir(parents=True, exist_ok=True)
        has_existing = (user_dir / "profile.json").exists()
    else:
        # Interactive startup menu
        result = run_startup_menu()
        if result is None:
            return
        user_dir, dir_name, has_existing = result

    profile_path = user_dir / "profile.json"

    # ── Check for existing profile ───────────────────────────────────

    if has_existing and profile_path.exists() and not args.rebuild:
        print("\n  📋 Found existing profile for '{}'".format(dir_name))
        existing = json.loads(profile_path.read_text())
        display_profile_summary(existing)

        if not ask_user_yes_no("Rebuild this profile from scratch?", "n"):
            print("\n  ✅ Keeping existing profile. Use --rebuild to start over.")
            print("  ➡️  Next: python3 scripts/score_jobs.py --profile {}".format(profile_path))
            return

    # ── Document check ───────────────────────────────────────────────

    doc_result = run_document_check(user_dir)

    if doc_result is None:
        print("\n  👋 No problem! Drop your files into {} and run again.".format(user_dir))
        return

    classified, other_files = doc_result

    # ── Read all documents ───────────────────────────────────────────

    print("\n  📖 Reading documents...")
    documents = {}

    for doc_type, path in classified.items():
        content = read_file(path)
        if content:
            documents[doc_type] = content
            print("    ✅ {}: {} chars".format(DOC_LABELS.get(doc_type, doc_type), len(content)))
        else:
            print("    ⚠️  {}: could not read".format(DOC_LABELS.get(doc_type, doc_type)))

    for path in other_files:
        content = read_file(path)
        if content:
            key = "additional_{}".format(path.stem)
            documents[key] = content
            print("    ✅ {}: {} chars".format(path.name, len(content)))

    if not documents:
        print("\n  ❌ Could not read any documents. Check file formats.")
        return

    # ── Extract with Claude ──────────────────────────────────────────

    extracted = extract_profile_from_docs(documents)

    if not extracted:
        print("  ❌ Could not extract profile data. Check your API key and try again.")
        return

    p = extracted.get("personal", {})
    print("\n  ✅ Extraction complete!")
    print("  " + "─" * 50)
    print("  Name detected:  {}".format(p.get("name", "Unknown")))
    print("  Roles detected: {}".format(", ".join(extracted.get("extracted_roles", [])[:4])))
    print("  Skills found:   {}".format(len(extracted.get("hard_skills", []))))
    print("  Experience:     {} years".format(extracted.get("years_of_experience", "?")))

    # ── Run interactive Q&A ──────────────────────────────────────────

    profile = run_interactive_qa(extracted)

    # ── Save profile ─────────────────────────────────────────────────

    profile_path.write_text(json.dumps(profile, indent=2))
    display_profile_summary(profile)

    print("\n  📁 Saved to: {}".format(profile_path))
    print("\n  ➡️  Next steps:")
    print("     1. Review: cat {}".format(profile_path))
    print("     2. Find jobs: python3 scripts/score_jobs.py --profile {}".format(profile_path))
    print("     3. Or re-run: python3 scripts/build_profile_v2.py --name {} --rebuild".format(dir_name))


if __name__ == "__main__":
    main()
